# Generated by Django 4.2.2 on 2023-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bio_alter_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='what is your bio', max_length=100),
        ),
    ]
